azs:
- name: z1
  cloud_properties: {availability_zone: <redacted>}
vm_types:
- name: default
  cloud_properties:
    instance_type: medium_2_4
networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.0.0/24
    gateway: 192.168.0.1
    reserved: [192.168.0.2-192.168.0.10]
    az: z1
    static: [192.168.0.13-192.168.0.100]
    cloud_properties: {net_id: f4ae...}
- name: compilation
  type: dynamic
  subnets:
    - az: z1
      cloud_properties: {net_id: f4ae...}
- name: vip
  type: vip
compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  vm_type: default
  network: compilation
